phpqa:
  tools:
    - phpcs:0
    - phpcpd:0
    - phpstan:0
    - phpmd:0
    - pdepend:0
    - phploc:0
    - phpmetrics:0
    - psalm:0      
phpcs:
  standard: tests/phpcs-standards/A6A
phpmd:
  standard: phpmd.xml
psalm:
  config: psalm.xml

